{{- if .Values.valkey.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-plane.name" . }}-valkey
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: valkey
  selector:
    app: valkey
{{- end }}
