{{- if .Values.quickwit.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-plane.name" . }}-quickwit
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  ports:
  - port: 7280
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: quickwit
{{- end }}
