{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-plane.name" . }}-mysql
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql
{{- end }}
